version: "3.3"
 
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=wb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - "5532:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  nats-streaming:
    image: nats-streaming
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
  adminer:
    image: adminer
    restart: always
    ports:
      - "9080:8080"